---
title: "Untitled"
output: html_document
date: "2023-08-17"
---

# setup

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'D:/02-sequences/')
# knitr::opts_knit$set(root.dir = '/scratch/users/cbowers/sequences/')
# knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(results = 'hold', fig.show = 'hold', fig.align = 'center')
# rm(list=ls())

```

```{r}
## load packages & functions
source('_data/setup.R')
source('_scripts/create_df_functions.R')

## additional packages
require(ncdf4)

## define custom function to convert .nc array output to raster bricks
array_to_raster <- function(x, lon_subset, lat_subset) {
  x %>% 
    aperm(c(2,1,3)) %>% 
    brick(
      xmn = min(lon_subset)-xres/2, xmx = max(lon_subset)+xres/2,
      ymn = min(lat_subset)-yres/2, ymx = max(lat_subset)+yres/2,
      crs = projection(wus)) %>%
    raster::flip('y')
}

```

# Brands

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Brands/MERRA2.ar_tag.Brands_v3.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Brands/MERRA2.ar_tag.Brands_v3.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_brands.Rdata')

```

# CASCADE

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/CASCADE/MERRA2.ar_tag.CASCADE_IVT.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/CASCADE/MERRA2.ar_tag.CASCADE_IVT.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
    }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_cascade.Rdata')

```

# CONNECT

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/CONNECT/IVT500_CONNECT_BinaryObjects_1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lon <- ifelse(lon >= 180, lon-360, lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/CONNECT/IVT500_CONNECT_BinaryObjects_',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_connect.Rdata')

```

# Gershunov

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Gershunov/MERRA2.ar_tag.Gershunovetal2017_v1.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Gershunov/MERRA2.ar_tag.Gershunovetal2017_v1.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_gershunov.Rdata')

```

# Goldenson

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Goldenson/MERRA2.ar_tag.Goldenson_v1.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Goldenson/MERRA2.ar_tag.Goldenson_v1.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_goldenson.Rdata')

```

# GuanWaliser

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/GuanWaliser/MERRA2.ar_tag.Guan_Waliser_v2.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/GuanWaliser/MERRA2.ar_tag.Guan_Waliser_v2.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_guanwaliser.Rdata')

```

# LBNL

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/LBNL/MERRA2.ar_tag.TDA_ML.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2016) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/LBNL/MERRA2.ar_tag.TDA_ML.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_lbnl.Rdata')

```

# Lora

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Lora/MERRA2.ar_tag.Lora_NPac.3hourly.19800101-19801231.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lon <- ifelse(lon >= 180, lon-360, lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2016) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Lora/MERRA2.ar_tag.Lora_NPac.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_lora.Rdata')

```

# Mattingly

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Mattingly/MERRA2.ar_tag.Mattingly_v2.3hourly.19800101-19801231.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Mattingly/MERRA2.ar_tag.Mattingly_v2.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_mattingly.Rdata')

```

# Mundhenk

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Mundhenk/MERRA2.ar_tag.Mundhenk_v2.3hourly.19800101-19801231.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2016) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Mundhenk/MERRA2.ar_tag.Mundhenk_v2.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_mundhenk.Rdata')

```

# PayneMagnusdottir

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/PayneMagnusdottir/MERRA2.ar_tag.Payne_Magnusdottir_2016.3hourly.1980.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/PayneMagnusdottir/MERRA2.ar_tag.Payne_Magnusdottir_2016.3hourly.',yr,'.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_paynemagnusdottir.Rdata')

```

# Rutz

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Rutz/MERRA2.ar_tag.Rutz.3hourly.19800101-19801231.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2016) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Rutz/MERRA2.ar_tag.Rutz.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_rutz.Rdata')

```

# SCAFET

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/SCAFET/MERRA2.ar_tag.SCAFET_v1.3hourly.19800101-19801231.nc')

# nc$dim$time
# (ymd_hms('1980-1-1 3:00:00') + hours(ncvar_get(nc, 'time'))) %>% month %>% table
# ts_artmip[year(ymd_hms(ts_artmip))==1980] %>% ymd_hms %>% month %>% table

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lon <- ifelse(lon >= 180, lon-360, lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2017) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/SCAFET/MERRA2.ar_tag.SCAFET_v1.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_scafet.Rdata')

```

# Walton

```{r}
nc <- nc_open('_data/ARTMIP/Tier 1/Walton/MERRA2.ar_tag.Walton_v1.3hourly.19800101-19801231.nc')

## download lat & lon
lon <- ncvar_get(nc, 'lon'); head(lon)
lat <- ncvar_get(nc, 'lat'); head(lat)

## subset global grid to NE Pacific + WUS
lon_subset <- lon[lon >= -150 & lon <= -110]
lat_subset <- lat[lat >= 20 & lat <= 60]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## get AR mask data
ardt <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count)
nc_close(nc)

mean(array_to_raster(ardt, lon_subset, lat_subset)) %>%
  raster.df %>% ggplot() +
  geom_raster(aes(x=x, y=y, fill = value)) +
  geom_sf(data = conus, fill = NA) + 
  coord_sf(xlim = c(-150,-110)) + 
  scale_fill_scico(palette = 'devon', direction = -1)

```

```{r}
## subset global grid to California
lon_subset <- lon[(lon+xres/2) %in% unique(coordinates(grid_ca)[,'x'])]
lat_subset <- lat[(lat+yres/2) %in% unique(coordinates(grid_ca)[,'y'])]

## find indices of lat/lon subset within global grid
lon.match <- which(lon %in% lon_subset)
lat.match <- which(lat %in% lat_subset)
dim.start <- c(min(lon.match), min(lat.match), 1)
dim.count <- c(length(lon.match), length(lat.match), -1)

## loop over years and combine
pb <- txtProgressBar(min = 1980, max = 2017, style = 3)
ardt <- 
  foreach (yr = 1980:2016) %do% {
    setTxtProgressBar(pb,yr)
    filename <- paste0(
      '_data/ARTMIP/Tier 1/Walton/MERRA2.ar_tag.Walton_v1.3hourly.',yr,'0101-',yr,'1231.nc')
    nc <- nc_open(filename)
    temp <- ncvar_get(nc, 'ar_binary_tag', start = dim.start, count = dim.count) %>% 
      array_to_raster(., lon_subset, lat_subset)
    nc_close(nc)
    temp
  }
save(ardt, file = '_data/ARTMIP/Tier 1/ardt_walton.Rdata')

```

# not used 

## x [Shields]

only includes landfall locations, not valid for all of CA

## x [PNNL]

all of the files are zero bytes

## x [Viale]

only South America


